### ISSUE TITLE
ebay request token from postman failed with "invalid client" error

### ISSUE THREAD

**Issue by matteoagora** [michabbb/ebay-oauth-playground#2]
error:"invalid client" ebay request token
![2022-05-17 12_59_17-Postman](https://user-images.githubusercontent.com/105720180/168803913-a088f842-c36e-4739-85fe-0eb6f6f1655e.jpg)

**Comment by michabbb** [comment]
hi, a screenshot doesn´t tell you more, just because u post it somewhere else.  because problems like these can have tons of reasons it´s extremely unproductive helping by writing back and forth. the best help I can offer is to check your stuff together within a screen share session. if you are interested, feel free to contact me via email: `info at macropage.de`.

**Comment by matteoagora** [comment]
of course, sorry but I'm new to these things and I don't know how to use all the tools yet.
The screenshot was to make you understand the topic. I have checked all the parameters and everything looks ok but it doesn't work. I thought maybe this error depended on something specific and the solution was relatively simple
